name: binder_env
channels:
- defaults
dependencies:
- pandas=0.22.0
- python=3.6.8
- pip
- tensorflow=1.2.0
- opencv
- pip:
  - tensorflow==1.12.0
  - keras==2.2.4
  - astropy==4.0.1
  - numpy==1.16.1
  - scipy==1.2.0
  - scikit-learn==0.20.3
  - scikit-image==0.15.0
  - matplotlib==3.1.0
  - opencv-python 
